name = "Endos"
uuid = "01662707-e366-4c4a-a509-54f5bf78c792"
authors = ["Frames White <me@oxinabox.net> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
